AWSTemplateFormatVersion: 2010-09-09
Description: Reference Architecture to host Moodle on AWS - Creates ElastiCache cache cluster
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Cache Parameters
      Parameters:
        - ElastiCacheNodeType
        - ElastiCacheClusterName
        - ElastiCacheSecurityGroup
        - Subnet
        - NumberOfAZs
    ParameterLabels:
      NumberOfAZs:
        default: Number of Availability Zones
      ElastiCacheClusterName:
        default: Cache Cluster Name
      ElastiCacheNodeType:
        default: Cache Cluster Node Type
      ElastiCacheSecurityGroup:
        default: ElastiCache Security Group
      Subnet:
        default: Subnets

Parameters:
  NumberOfAZs:
    AllowedValues:
    - 2
    - 2
    - 3
    - 4
    - 5
    - 6
    Default: 2
    Description: Number of Availability Zones to use in the VPC. This must match your
      selections in the list of Availability Zones parameter.
    Type: Number
  ElastiCacheClusterName:
    AllowedPattern: ^([a-zA-Z0-9]*)$
    Description: The ElastiCache cluster name. Defaults to the Amazon RDS database name.
    Type: String
  ElastiCacheNodeType:
    AllowedValues:
      - cache.t3.micro
      - cache.t3.small
      - cache.t3.medium
      - cache.m5.large
      - cache.m5.xlarge
      - cache.m5.2xlarge
    ConstraintDescription: Must be a valid Amazon ElastiCache node type.
    Default: cache.t3.micro
    Description: The Amazon ElastiCache cluster node type.
    Type: String
  ElastiCacheSecurityGroup:
    Description: Select the ElastiCache security group.
    Type: AWS::EC2::SecurityGroup::Id
  Subnet:
    Description: Select existing subnets. The number selected must match the number of subnets above. Subnets selected must be in separate AZs.
    Type: List<AWS::EC2::Subnet::Id>

Resources:
  #ElastiCacheCluster:
    #Type: AWS::ElastiCache::ReplicationGroup
    #Properties:
      #ReplicationGroupId: !Ref ElastiCacheClusterName
      #ReplicationGroupDescription: !Ref ElastiCacheClusterName
      #AtRestEncryptionEnabled: true
      #TransitEncryptionEnabled: false
      #AutoMinorVersionUpgrade: false
      #MultiAZEnabled: true
      #CacheNodeType: !Ref ElastiCacheNodeType
      #CacheSubnetGroupName: !Ref ElastiCacheSubnetGroup
      #Engine: redis
      #EngineVersion: 6.2
      #NumCacheClusters:
        #!Ref NumberOfAZs
      #Tags:
        #- Key: Name
          #Value: !Join [ '', [ 'Moodle / ', !Ref 'AWS::StackName' ] ]
      #SecurityGroupIds:
      #- !Ref ElastiCacheSecurityGroup
  ElastiCacheCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      AZMode: cross-az
      CacheNodeType: !Ref ElastiCacheNodeType
      CacheSubnetGroupName: !Ref ElastiCacheSubnetGroup
      ClusterName: !Ref ElastiCacheClusterName
      Engine: memcached
      NumCacheNodes: !Ref NumberOfAZs
      Tags:
        - Key: Name
          Value: !Join [ '', [ 'Moodle / ', !Ref 'AWS::StackName' ] ]
      VpcSecurityGroupIds:
      - !Ref ElastiCacheSecurityGroup        
  ElastiCacheSubnetGroup: 
    Type: AWS::ElastiCache::SubnetGroup
    Properties: 
      CacheSubnetGroupName: !Join [ '', [ !Ref ElastiCacheClusterName, SubnetGroup ] ]
      Description: ElastiCache Subnet Group for Moodle
      SubnetIds: !Ref Subnet

Outputs:
  ElastiCacheClusterEndpointAddress:
    #Value: !GetAtt ElastiCacheCluster.PrimaryEndPoint.Address
    Value: !GetAtt ElastiCacheCluster.ConfigurationEndpoint.Address